config/routes.rb
Rails.application.routes.draw do
  get 'select/select'

  resources :select
  post '/next_question', to: 'questions#next_question'
  root 'top#index'
  get 'top/index'
  get 'list/testA'
  get 'list/testB'
  get 'list/testS'
  get 'preview/prevQ'
  get 'preview/prevA'
  get 'preview/delete'
  
  get 'top/index', to: 'top#index'
  get 'preview/prevQ/:id', to: 'preview#prevQ', as: :preview_question

  resources :questions, only: [:new, :create, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/option.rb
class Option < ApplicationRecord
    belongs_to :question

    validates :content, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :options, dependent: :destroy
  
    accepts_nested_attributes_for :options
  
    validates :title, presence: true
    validates :question_text, presence: true
    validates :name, presence: true
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    

    begin
        @@message
    rescue
        @@message = ""
    end

    begin
        @@message2
    rescue
        @@message2 = ""
    end

end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def testA
    puts "##########################"
    puts params
    case params[:action_type]
      when 'startA'
        @@message = '基本情報技術者試験（A試験）'
        @@message2 = '試験実施'
      when 'listA'
        @@message = '基本情報技術者試験（A試験）'
        @@message2 = '問題一覧'
      when 'startB'
        @@message = '基本情報技術者試験（B試験）'
        @@message2 = '試験実施'
      when 'listB'
        @@message = '基本情報技術者試験（B試験）'
        @@message2 = '問題一覧'
      when 'startS'
        @@message = 'Ruby Silver/試験実施'
        @@message2 = '試験実施'
      when 'listS'
        @@message = 'Ruby Silver/問題詳細'
        @@message2 = '問題一覧'
      #///////////////////ここから問題一覧内のボタン////////////////

      when 'createQ'
        @@message2 = '問題作成'
      when 'prev'
        @@message2 = '問題詳細'

      #//////////////////////////////////////////////////////////

      
    end
      puts @@message
      @title = @@message
      @title2 = @@message2
  end

  
end

app/controllers/preview_controller.rb
class PreviewController < ApplicationController
    def prevQ
        prevpanlist
      end

      def prevA
      prevpanlist
      end

      private
      def prevpanlist
        puts "#########prevC!!!!!!!!!!!!###########"
        puts params
        case params[:action_type]
          #///////////////////ここから問題一覧内のボタン////////////////
    
          when 'createQ'
            @@message2 = '問題作成'
          when 'prevQ'
            @@message2 = '問題詳細'
          when 'prevA'
            @@message2 = '解答詳細'
    
          #//////////////////////////////////////////////////////////
    
         
        end
          puts @@message
          @title = @@message
          @title2 = @@message2
    end
      
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
    4.times { @question.options.build }
  end

  def create
    @question = Question.new(question_params)

    correct_option_index = params[:correct_option].to_i

    @question.options.each_with_index do |option, index|
      option.answers = (index == correct_option_index)
    end

    if @question.save
      redirect_to @question, notice: "問題が登録されました。"
    else
      flash.now[:alert] = "入力されていない項目があります"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  # 更新画面

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.assign_attributes(question_params)
  
    correct_option_index = params[:correct_option].to_i
  
    @question.options.each_with_index do |option, i|
      option.answers = (i == correct_option_index)
    end
  
    if @question.save
      redirect_to @question, notice: "問題を更新しました。"
    else
      flash.now[:alert] = "入力されていない項目があります"
      render :edit, status: :unprocessable_entity
    end
  end
  

  private

  def question_params
    params.require(:question).permit(
      :name,
      :title,
      :question_text,
      :explanation,
      options_attributes: [:id, :content]
    )
  end  
end

app/controllers/select_controller.rb
class SelectController < ApplicationController
    def Select
        
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
        puts "####index######################"
    puts params
    case params[:action_type]
    when 'startA'
        @@message = '基本情報技術者試験（A試験）/試験実施'
    when 'listA'
        @@message = '基本情報技術者試験（A試験）/問題詳細'
    when 'startB'
        @@message = '基本情報技術者試験（B試験）/試験実施'
    when 'listB'
        @@message = '基本情報技術者試験（B試験）/問題詳細'
    when 'startS'
        @@message = 'Ruby Silver/試験実施'
    when 'listS'
        @@message = 'Ruby Silver/問題詳細'
    
    end
    puts @@message
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/preview_helper.rb
module PreviewHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/select_helper.rb
module SelectHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>study</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
    　<%= image_tag 'Study.png', class:'topicon' %>
      <%= button_to 'HOME', top_index_path, method: :get, class: 'btn-home' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/list/testA.html.erb
<main class="list">
    <div class="center">
        <p class="current"><%= @title %>/<%= @title2 %></p>

        <div class="list_box">
            <div class="box_left">
                <div class="left_top">
                    <h1>ジャンル名</h1>
                    <h2>正答率：〇％</h2>
                </div>
                <p>▶ここに問題文の一部が入るのだ。文末は…ここの長さで幅変わってる？？やっぱそうらしい。改行は？されてるね。改善しましたので長さ固定できました。</p>
            </div>
            <div class="box_right">
                <p>登録日：2024.06.27</p>
                <p>登録者：BE</p>
                <%= button_to '▶プレビュー', preview_prevQ_path, method: :get, class: 'preview_btn', params: { action_type: 'prev' } %>
            </div>
        </div>


        <!-- ボタンクリック後の移動先をまだ設定していないです -->
        <%= button_to '問題を作る', list_testA_path, method: :get, class: 'create_btn', params: { action_type: 'createQ' } %>
    </div>
</main>

app/views/list/testB.html.erb
<p class="current"><%= @title %>/<%= @title2 %></p>

<!-- testAが整ってから記述 -->

app/views/list/testS.html.erb
<p class="current"><%= @title %>/<%= @title2 %></p>

<!-- testAが整ってから記述 -->

app/views/preview/delete.html.erb
<p class="current"><%= @title %>/<%= @title2 %></p>

<div class="btn_right">
    <%= button_to '中止する', list_testA_path, method: :get, class: 'answer_btn' %>
    <%= button_to '削除する', list_testA_path, method: :get, class: 'delete_btn' %>
</div>

app/views/preview/prevA.html.erb
<main class="prev">
    <p class="current"><%= @title %>/<%= @title2 %></p>
    <p>kaitou</P>
    <div class="prev_btn">
        <%= button_to '問題一覧へ', list_testA_path, method: :get, class: 'list_btn', params: { action_type: 'prev' } %>
        <div class="btn_right">
            <%= button_to '▶問題', preview_prevQ_path, method: :get, class: 'answer_btn', params: { action_type: 'prevQ' } %>
            <%= button_to '▶編集', list_testA_path, method: :get, class: 'edit_btn', params: { action_type: 'prev' } %>
            <%= button_to '▶削除', preview_delete_path, method: :get, class: 'delete_btn', params: { action_type: 'prev' } %>
        </div>
    </div>
</main>

app/views/preview/prevQ.html.erb
<main class="prev">
    <p class="current"><%= @title %>/<%= @title2 %></p>
    <p>aiueo</P>
    <div class="Q_box">
        <p class="Q_sentence">仮想記憶機能を持つパソコンで表計算ソフトを使用中にワープロソフトを使用しようとしたところ、メモリ不足が原因で起動できなかった。根本的な解決はメモリ増設であるが、それまでの対応として、有効な手段はどれか。</p>
    </div>
    <div class="prev_btn">
        <%= button_to '問題一覧へ', list_testA_path, method: :get, class: 'list_btn', params: { action_type: 'prev' } %>
        <div class="btn_right">
            <%= button_to '▶解答', preview_prevA_path, method: :get, class: 'answer_btn', params: { action_type: 'prevA' } %>
            <%= link_to '▶編集', edit_question_path(@question), class: "edit_btn", params: { action_type: 'prev' } %>
            <%= button_to '▶削除', preview_delete_path, method: :get, class: 'delete_btn', params: { action_type: 'prev' } %>
        </div>
    </div>
</main>

<!-- 問題一覧ボタン、編集ボタン、削除ボタンの移行先等未 -->

app/views/questions/edit.html.erb
<main>
    <div class="question-form-wrapper">
        <%= form_with model: @question, local: true do |form| %>
          <div class="form-group">
            <%= form.label :name, "登録者", class: "label-blue" %><br>
            <%= form.text_field :name, placeholder: "登録者を入力", class: "text-input" %>
          </div>
    
          <div class="form-group">
            <%= form.label :title, "ジャンル", class: "label-blue" %><br>
            <%= form.text_field :title, placeholder: "ジャンルを入力", class: "text-input" %>
          </div>
    
          <div class="form-group">
            <%= form.label :question_text, "問題文", class: "label-blue" %><br>
            <%= form.text_area :question_text, placeholder: "問題文を入力", class: "text-input" %>
          </div>
    
          <% letters = ["ア","イ","ウ","エ"] %>
    
          <fieldset class="form-group">
            <legend>選択肢</legend>
            <%= form.fields_for :options do |option_form| %>
              <% i = option_form.index %>
              <div class="form-group">
                <%= option_form.label :content, "選択肢：#{letters[i]}", class: "label-blue" %><br>
                <%= option_form.text_field :content, placeholder: "選択肢を入力", class: "text-input" %>
              </div>
            <% end %>
          </fieldset>
    
          <fieldset class="form-group">
            <legend class="label-blue">解答</legend>
            <% @question.options.each_with_index do |option, index| %>
              <label class="radio-button">
                <%= radio_button_tag "correct_option", index, option.answers %>
                <span class="label-blue"><%= letters[index] %></span>
              </label>
            <% end %>
          </fieldset>
    
          <div class="form-group">
            <%= form.label :explanation, "解説", class: "label-blue" %><br>
            <%= form.text_area :explanation, placeholder: "解説を入力", class: "text-input" %>
          </div>
    
          <div class="button-group">
            <%= link_to "中止する", "#", id: "cancel-btn", class: "button-tyuusi" %>
            <%= form.submit "上書きして保存", class: "button" %>
          </div>
    
        <% end %>
    </div>
</main>

app/views/questions/new.html.erb
<main>
  <div class="question-form-wrapper">
    <%= form_with model: @question, local: true do |form| %>
      <div class="form-group">
        <%= form.label :name, "登録者", class: "label-blue" %>
        <%= form.text_field :name, placeholder: "名前を入力してください。", class: "text-input" %>
      </div>

      <div class="form-group">
        <%= form.label :title, "ジャンル", class: "label-blue" %><br>
        <%= form.text_field :title, placeholder: "ジャンルを入力してください。", class: "text-input" %>
      </div>

      <div class="form-group">
        <%= form.label :question_text, "問題文", class: "label-blue" %><br>
        <%= form.text_area :question_text, placeholder: "問題を入力してください。", class: "text-input" %>
      </div>

      <% letters = ["ア","イ","ウ","エ"] %>
      <fieldset class="form-group">
        <%= form.fields_for :options do |option_form| %>
          <% i = option_form.index %>
          <div class="form-group">
            <%= option_form.label :content, "選択肢：" + letters[i], class: "label-blue" %><br>
            <%= option_form.text_field :content, placeholder: "選択項目を入力してください。", class: "text-input" %>
          </div>
        <% end %>
      </fieldset>

      <fieldset class="form-group">
        <legend class="label-blue">解答</legend>
        <% @question.options.each_with_index do |option, index| %>
          <label class="radio-button">
            <%= radio_button_tag "correct_option", index %>
            <span class="label-blue"><%= letters[index] %></span>
          </label>
        <% end %>
      </fieldset>

      <div class="form-group">
        <%= form.label :explanation, "解説", class: "label-blue" %><br>
        <%= form.text_area :explanation, placeholder: "解説を入力してください。", class: "text-input" %>
      </div>

      <div class="button-group">
        <%= link_to "中止する", "#", id: "cancel-btn", class: "button-tyuusi" %>
        <%= form.submit "▶登録", class: "button" %>
      </div>

      <% if flash[:alert].present? %>
        <div class="error-message">
          <%= flash[:alert] %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="cancel-modal" class="modal">
    <div class="modal-content">
      <h2>注意</h2>
      <hr>
      <p>入力された内容が破棄されます。<br>よろしいですか？</p>
      <div class="modal-buttons">
        <button id="cancel-confirm-button" class="button-tyuusi">中止する</button>
        <button id="cancel-close-button" class="button">キャンセル</button>
      </div>
    </div>
  </div>
</main>

app/views/questions/show.html.erb
<main>
  <h2>タイトル: <%= @question.title %></h2>
  <p>登録者: <%= @question.name %></p>
  <p>問題文: <%= @question.question_text %></p>

  <hr>

  <h3>選択肢</h3>
  <ul>
    <% @question.options.each_with_index do |option, index| %>
      <li>
        <%= ('ア'..'エ').to_a[index] %>: <%= option.content %>
        <% if option.answers %>
          <strong>（正解）</strong>
        <% end %>
      </li>
    <% end %>
  </ul>

  <hr>

  <h3>解説</h3>
  <p><%= @question.explanation %></p>
</main>

app/views/select/answer_detail.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>基本情報技術者試験</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: linear-gradient(to bottom, #dce4ed, #aebccf);
            text-align: center;
        }
        .container {
            width: 60%;
            margin: 50px auto;
            padding: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.2);
            text-align: left;
            padding-bottom: 30px;
        }
        h2 {
            background-color: #34568B;
            color: white;
            padding: 10px;
            border-radius: 5px;
            text-align: left;
            margin-top: 0;
        }
        .question-box {
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .option {
            display: flex;
            align-items: center;
            background-color: white;
            border: 2px solid #ccc;
            padding: 10px;
            border-radius: 5px;
            cursor: pointer;
            transition: 0.3s;
            font-size: 18px;
        }
        .option.selected {
            background-color: #f39c12;
            color: white;
            border-color: #e67e22;
        }
        .button-container {
            text-align: center;
            margin-top: 20px;
        }
        .submit-button {
            background-color: #f39c12;
            border: none;
            padding: 10px 20px;
            color: white;
            font-size: 18px;
            cursor: pointer;
            border-radius: 5px;
        }
        .answer-explanation {
            background-color: #f1c40f;
            padding: 15px;
            border-radius: 8px;
            margin-top: 20px;
            font-size: 18px;
            display: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Study</h2>
        <p><strong>基本情報技術者試験（A試験） / 試験実施</strong></p>

        <!-- 第1問 -->
        <div class="question-box" id="question1">
            <p><strong>第1問</strong></p>
            <p>仮想記憶機能を持つパソコンで表計算ソフトを使用中にワープロソフトを使用しようとしたところ、
                メモリ不足が原因で起動できなかった。根本的な解決はメモリ増設であるが、それまでの対応として、
                有効な手段はどれか。</p>
            <div class="options">
                <label class="option"><input type="radio" name="answer1" value="ア"> ア 仮想記憶の大きさの設定値を増やす。</label>
                <label class="option"><input type="radio" name="answer1" value="イ"> イ 磁気ディスク上の不要なファイルを削除する。</label>
                <label class="option"><input type="radio" name="answer1" value="ウ"> ウ 接続してある周辺機器を外す。</label>
                <label class="option"><input type="radio" name="answer1" value="エ"> エ ワークシート中の未使用の列は、表示しないようにする。</label>
            </div>
        </div>

        <!-- 第1問 解説 -->
        <div class="answer-explanation" id="answer-explanation1">
            <p><strong>回答: ア</strong></p>
            <p>仮想記憶の大きさの設定を増やすことで、メモリ不足の問題を解消する可能性が高いです。</p>
            <div class="button-container">
                <button class="submit-button" onclick="nextQuestion()">次の問題へ</button>
            </div>
        </div>

        <div class="button-container">
            <button class="submit-button" onclick="showAnswer(1)">回答する</button>
        </div>

        <!-- 第2問 -->
        <div class="question-box" id="question2" style="display: none;">
            <p><strong>第2問</strong></p>
            <p>仮想記憶機能の設定を変更することで、メモリ不足の問題を解決できる可能性がある。
                どの設定を変更すべきか。</p>
            <div class="options">
                <label class="option"><input type="radio" name="answer2" value="ア"> ア ページングファイルのサイズを増やす。</label>
                <label class="option"><input type="radio" name="answer2" value="イ"> イ ディスクのデフラグを行う。</label>
                <label class="option"><input type="radio" name="answer2" value="ウ"> ウ インデックス検索を無効にする。</label>
                <label class="option"><input type="radio" name="answer2" value="エ"> エ ネットワーク共有フォルダを減らす。</label>
            </div>
        </div>

        <!-- 第2問 解説 -->
        <div class="answer-explanation" id="answer-explanation2" style="display: none;">
            <p><strong>回答: ア</strong></p>
            <p>ページングファイルのサイズを増やすことで、仮想メモリを拡張し、メモリ不足を緩和できます。</p>
        </div>

        <div class="button-container">
            <button class="submit-button" onclick="showAnswer(2)">回答する</button>
        </div>
    </div>

    <script>
        function showAnswer(questionNumber) {
            const selectedOption = document.querySelector(`input[name="answer${questionNumber}"]:checked`);
            if (!selectedOption) {
                alert("回答が選択されていません！");
                return;
            }
            document.getElementById(`answer-explanation${questionNumber}`).style.display = "block";  
            document.getElementById(`question${questionNumber}`).style.display = "none";  
        }

        function nextQuestion() {
            document.getElementById("answer-explanation1").style.display = "none";  
            document.getElementById("question2").style.display = "block";  
        }
    </script>
</body>
</html>

app/views/select/select.html.erb
<main>        
        <p><strong>基本情報技術者試験（A試験） / 試験実施</strong></p>

        <!-- 第1問 -->
        <div class="question-box" id="question1">
            <p><strong>第1問</strong></p>
            <p>仮想記憶機能を持つパソコンで表計算ソフトを使用中にワープロソフトを使用しようとしたところ、
                メモリ不足が原因で起動できなかった。根本的な解決はメモリ増設であるが、それまでの対応として、
                有効な手段はどれか。</p>
            <div class="options">
                <label class="option" onclick="selectOption(this, 'answer1')"><input type="radio" name="answer1" value="ア"> ア </label> <e>仮想記憶の大きさの設定値を増やす。</e>
                <label class="option" onclick="selectOption(this, 'answer1')"><input type="radio" name="answer1" value="イ"> イ </label> <e>磁気ディスク上の不要なファイルを削除する。</e>
                <label class="option" onclick="selectOption(this, 'answer1')"><input type="radio" name="answer1" value="ウ"> ウ </label> <e>接続してある周辺機器を外す。</e>
                <label class="option" onclick="selectOption(this, 'answer1')"><input type="radio" name="answer1" value="エ"> エ </label> <e>ワークシート中の未使用の列は、表示しないようにする。</e>
            </div>
            <div class="button-container">
                <button class="submit-button" onclick="showAnswer(1)">回答する</button>
            </div>
        </div>

        <!-- 第1問 解説 -->
        <div class="answer-explanation" id="answer-explanation1">
            <p><strong>回答: ア</strong></p>
            <p>仮想記憶の大きさの設定を増やすことで、メモリ不足の問題を解消する可能性が高いです。</p>
            <div class="button-container">
                <button class="submit-button" onclick="nextQuestion()">次の問題へ</button>
            </div>
        </div>

        <!-- 第2問 -->
        <div class="question-box" id="question2" style="display: none;">
            <p><strong>第2問</strong></p>
            <p>仮想記憶機能の設定を変更することで、メモリ不足の問題を解決できる可能性がある。
                どの設定を変更すべきか。</p>
            <div class="options">
                <label class="option" onclick="selectOption(this, 'answer2')"><input type="radio" name="answer2" value="ア"> ア </label> ページングファイルのサイズを増やす。
                <label class="option" onclick="selectOption(this, 'answer2')"><input type="radio" name="answer2" value="イ"> イ </label> ディスクのデフラグを行う。
                <label class="option" onclick="selectOption(this, 'answer2')"><input type="radio" name="answer2" value="ウ"> ウ </label> インデックス検索を無効にする。
                <label class="option" onclick="selectOption(this, 'answer2')"><input type="radio" name="answer2" value="エ"> エ </label> ネットワーク共有フォルダを減らす。
            </div>
            <div class="button-container">
                <button class="submit-button" onclick="showAnswer(2)">回答する</button>
            </div>
        </div>

        <!-- 第2問 解説 -->
        <div class="answer-explanation" id="answer-explanation2" style="display: none;">
            <p><strong>回答: ア</strong></p>
            <p>ページングファイルのサイズを増やすことで、仮想メモリを拡張し、メモリ不足を緩和できます。</p>
        </div>

        
                
    
</main>
<script href="application.js"></script>
    # <script>
    #     function selectOption(element, name) {
    #         document.querySelectorAll(`input[name="${name}"]`).forEach(input => {
    #             input.parentElement.classList.remove('selected');
    #         });
    #         element.classList.add('selected');
    #         element.querySelector('input').checked = true;
    #     }

    #     function showAnswer(questionNumber) {
    #         const selectedOption = document.querySelector(`input[name="answer${questionNumber}"]:checked`);
    #         if (!selectedOption) {
    #             alert("回答が選択されていません！");
    #             return;
    #         }
    #         document.getElementById(`answer-explanation${questionNumber}`).style.display = "block";  
    #         document.getElementById(`question${questionNumber}`).style.display = "none";  
    #     }

    #     function nextQuestion() {
    #         document.getElementById("answer-explanation1").style.display = "none";  
    #         document.getElementById("question2").style.display = "block";  
    #     }
    # </script>

app/views/top/index.html.erb
<main class="top">
    <div class="logo">
        <%= image_tag 'logo2.png', class:'icon' %>
        <h1>Welcome to Study</h1>
        <p>Studyは試験勉強に励む学生が<br>お互いを高めあうお手伝いをします</p>
    </div>

    <!-- ボタンクリック後の移動先をまだ設定していないです -->

    <div class="subject">
        <div class="subject_box">
            <div class="overview">
                <h1 class="subject_name">基本情報技術者試験（科目A）</h1>
                <div class="detail">
                    <p>試験時間：90分</p>
                    <p>出題形式：多肢選択式（四肢択一）</p>
                    <p>問題数　：60問</p>
                </div>
            </div>
            <div class="btn_top">
                <%= button_to '出題開始', top_index_path, method: :get, class: 'question_btn', params: { action_type: 'startA' } %>
                <%= button_to '問題一覧', list_testA_path, method: :get, class: 'List_btn', params: { action_type: 'listA' } %>
            </div>
        </div>

        <div class="subject_box">
            <div class="overview">
                <h1 class="subject_name">基本情報技術者試験（科目B）</h1>
                <div class="detail">
                    <p>試験時間：100分</p>
                    <p>出題形式：多肢選択式</p>
                    <p>問題数　：20問</p>
                </div>
            </div>
            <div class="btn_top">
                <%= button_to '出題開始', top_index_path, method: :get, class: 'question_btn', params: { action_type: 'startB' } %>
                <%= button_to '問題一覧', list_testB_path, method: :get, class: 'List_btn', params: { action_type: 'listB' } %>
            </div>
        </div>

        <div class="subject_box">
            <div class="overview">
                <h1 class="subject_name">Ruby Silver</h1>
                <div class="detail">
                    <p>試験時間：90分</p>
                    <p>出題形式：多肢選択式</p>
                    <p>問題数　：50問</p>
                </div>
            </div>
            <div class="btn_top">
                <%= button_to '出題開始', top_index_path, method: :get, class: 'question_btn', params: { action_type: 'startS' } %>
                <%= button_to '問題一覧', list_testS_path, method: :get, class: 'List_btn', params: { action_type: 'listS' } %>
            </div>
        </div>
    </div>

</main>